import time
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Exemplo de lista de bairros únicos — substitua pela sua lista
bairros = [
"bairro",
"70/RO",
"Aflitos",
"Afogados",
"Aguazinha",
"Alto Jardim Conquista",
"Alto José Bonifácio",
"Alto José do Pinho",
"Alto Nova Olinda",
"Alto Santa Terezinha",
"Alto da Bondade",
"Alto da Conquista",
"Alto da Nação",
"Alto do Mandu",
"Alto do Sol Nascente",
"Amaro Branco",
"Amparo",
"Apipucos",
"Areias",
"Arruda",
"Bairro Novo",
"Barra de Jangada",
"Barro",
"Beberibe",
"Benfica",
"Boa Viagem",
"Boa Vista",
"Bomba do Hemetério",
"Bongi",
"Bonsucesso",
"Brasília Teimosa",
"Brejo da Guabiraba",
"Bulhões",
"Bultrins",
"Cabanga",
"Caixa D'água",
"Cajueiro",
"Cajueiro Seco",
"Campina do Barreto",
"Campo Grande",
"Candeias",
"Carmo",
"Casa Amarela",
"Casa Caiada",
"Casa Forte",
"Cavaleiro",
"Caxangá",
"Caçote",
"Centro",
"Cidade Universitária",
"Coelhos",
"Cohab",
"Comportas",
"Coqueiral",
"Cordeiro",
"Curado",
"Curado I",
"Curado II",
"Curado III",
"Curado IV",
"Córrego do Abacaxi",
"Derby",
"Dois Carneiros",
"Dois Irmãos",
"Dois Unidos",
"Encruzilhada",
"Engenho Velho",
"Engenho do Meio",
"Espinheiro",
"Floriano",
"Fragoso",
"Fundão",
"Graças",
"Guabiraba",
"Guadalupe",
"Guararapes",
"Hipódromo",
"Ibura",
"Ilha Joana Bezerra",
"Ilha do Leite",
"Ilha do Retiro",
"Imbiribeira",
"Jaboatão Centro",
"Jaqueira",
"Jardim Atlântico",
"Jardim Brasil",
"Jardim Fragoso",
"Jardim Jordão",
"Jardim Piedade",
"Jardim São Paulo",
"Jatobá",
"Linha do Tiro",
"Macaxeira",
"Madalena",
"Madalena (Recife)",
"Manassu",
"Marcos Freire",
"Milagres",
"Monte",
"Morro da Conceição",
"Muribeca",
"Muribeca dos Guararapes",
"Muribequinha",
"Mussuré",
"Nova Descoberta",
"Nova Morada",
"Nova Olinda",
"Ouro Preto",
"Paissandu",
"Parnamirim",
"Passarinho",
"Pau Ferro",
"Peixinhos",
"Piedade",
"Pina",
"Ponto de Parada",
"Porto da Madeira",
"Poço da Panela",
"Prado",
"Praias",
"Prazeres",
"Recife Antigo",
"Rio Doce",
"Rosarinho",
"Salgadinho",
"San Martin",
"Sancho",
"Santa Tereza",
"Santana",
"Santo Aleixo",
"Santo Amaro",
"Santo Antônio",
"Sapucaia",
"Socorro",
"Soledade",
"Sucupira",
"São Benedito",
"São José",
"Sítio Novo",
"Sítio dos Pintos",
"Tabajara",
"Tamarineira",
"Tejipió",
"Torre",
"Torrões",
"Totó",
"Umuarama",
"Varadouro",
"Vargem Fria",
"Vasco da Gama",
"Vila Popular",
"Vila Rica",
"Vila do Ipsep",
"Vista Alegre",
"Várzea",
"Zona Rural",
"Zumbi",
"Zumbi do Pacheco",
"Água Fria",
"Águas Compridas",
"Área Rural de Jaboatão dos Guararapes"
]


geolocator = Nominatim(user_agent="meu_projeto_geocode")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)  # para não ultrapassar limite

resultados = []
for bairro in bairros:
    try:
        location = geocode(bairro)
        if location:
            lat = location.latitude
            lon = location.longitude
        else:
            lat = None
            lon = None
    except Exception as e:
        lat = None
        lon = None
    resultados.append({'bairro': bairro, 'latitude': lat, 'longitude': lon})
    print("Processado:", bairro, "->", lat, lon)
    time.sleep(1)  # para respeitar limites de requisição
    

df_coords = pd.DataFrame(resultados)
df_coords.to_csv('coords_bairros_geocoded.csv', index=False)
print("Arquivo gerado: coords_bairros_geocoded.csv")
